# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2019-01-29 16:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0002_auto_20190129_1608'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='views',
        ),
    ]
